NAME		=		PmergeMe

CXX			=		c++

OBJ_DIR		=		obj

CXXFLAGS	=		-std=c++98 -Wall -Wextra -Werror -MMD -MP

MAKEFLAGS	+=		--no-print-directory -j$(nproc)

###############################################################################
###								FILES										###
###############################################################################

MAKEFILE	=		Makefile

SRC			=		main.cpp PmergeMe.cpp

OBJ			=		$(SRC:%.cpp=$(OBJ_DIR)/%.o)

DEP			=		$(OBJ:%.o=%.d)

###############################################################################
###								ARCHIVES									###
###############################################################################

all: $(NAME)

$(NAME): $(OBJ)
			$(CXX) $(CXXFLAGS) $(OBJ) -o $(NAME)

$(OBJ_DIR)/%.o: %.cpp $(MAKEFILE) | $(OBJ_DIR)
			$(CXX) $(CXXFLAGS) -o $@ -c $<

$(OBJ_DIR):
			mkdir -p $(OBJ_DIR)

-include $(DEP)

re: fclean
			$(MAKE) all

fclean: clean
			rm -f $(NAME)

clean: 
			rm -rf $(OBJ_DIR)

.PHONY: all clean fclean re